Validation phase: False
Namespace(ips=999999, bs=4, nodw=10, ntibp=10, sd='SegNet', ptd='./sclera_data', is_test_run=True, pruning_phase=False, pbop=False, e_ix=3, mti=2, map=1000000000.0, nept=1, pnkao=20, nftp=1, rn='flops_num', ptp=0.01)
path to file: ./sclera_data
summary for train
valid images: 1288
summary for val
valid images: 344
summary for test
valid images: 208
train dataset len: 30
val dataset len: 30
test dataset len: 30
train dataloader num of batches: 8
val dataloader num of batches: 8
test dataloader num of batches: 8
Device: cuda
loss: 0.500723  [    4/   30]
loss: 0.508740  [    8/   30]
loss: 0.429065  [   12/   30]
loss: 0.468555  [   16/   30]
loss: 0.475856  [   20/   30]
loss: 0.481442  [   24/   30]
loss: 0.475264  [   28/   30]
loss: 0.450566  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
validation Error: 
 Avg loss: 0.45415981 
 IoU: 0.867218 
 F1: nan 

test Error: 
 Avg loss: 0.44703809 
 IoU: 0.874638 
 F1: nan 

loss: 0.485965  [    4/   30]
loss: 0.516417  [    8/   30]
loss: 0.509549  [   12/   30]
loss: 0.475109  [   16/   30]
loss: 0.476720  [   20/   30]
loss: 0.475631  [   24/   30]
loss: 0.467358  [   28/   30]
loss: 0.434475  [   16/   30]
/home/matevzvidovic/Desktop/Diplomska/Prototip/Delo/TrainingWrapper.py:225: RuntimeWarning: invalid value encountered in scalar divide
  precision = TP / (TP + FP)
validation Error: 
 Avg loss: 0.45375552 
 IoU: 0.867547 
 F1: nan 

test Error: 
 Avg loss: 0.45156172 
 IoU: 0.869886 
 F1: nan 

